services:
  python:
    build:
      context: .
      dockerfile: python.Dockerfile

    volumes:
      - ./:/app

    ports:
      - 8000:8000

    user: 1000:1000
    working_dir: /app

  node:
    build:
      context: .
      dockerfile: node.Dockerfile

    volumes:
      - ./:/app

    user: 1000:1000
    working_dir: /app
